config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations',
    passwords: 'users/passwords', confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  root 'home#index'

  namespace :users do
    resource :profiles, only: :show
  end
  resources :posting_threads
  resources :comments, only: [:create, :update, :destroy] do
    collection do
      post 'like'
    end
  end
  resources :search, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :posting_thread, touch: true, inverse_of: :comments

  validates :content, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
  validates :posting_thread_id, presence: true

  def good_or_bad?(user)
    like = likes.where(user_id: user.id).first
    like ? like.good_or_bad : ""
  end

  def poster
    user.name
  end

  def good_count
    likes.where(good_or_bad: "good").length
  end

  def bad_count
    likes.where(good_or_bad: "bad").length
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :like]

  def create
    @posting_thread = PostingThread.find params[:comment][:posting_thread_id]
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def like
    if @like = Like.find_by(user_id: current_user.id, comment_id: params[:like][:comment_id])
      @like.update(good_or_bad: params[:like][:good_or_bad])
    else
      @like = current_user.likes.new(like_params)
      @like.save
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :posting_thread_id)
    end

    def like_params
      params.require(:like).permit(:good_or_bad, :comment_id)
    end
end

app/views/comments/_bad_like.html.erb
<div class="col s6 center">
  <%= link_to like_comments_path(
    like: {
      good_or_bad: "good",
      comment_id: comment.id,
    }), remote: true, method: :post do %>
    <i class="material-icons light-blue-text text-lighten-4">thumb_up</i>
  <% end %>
</div>
<div class="col s6 center">
  <%= link_to like_comments_path(
    like: {
      good_or_bad: "",
      comment_id: comment.id
    }), remote: true, method: :post do %>
    <i class="material-icons light-blue-text text-lighten-1">thumb_down</i>
  <% end %>
</div>

app/views/comments/_both_unlike.html.erb
<div class="col s6 center">
  <%= link_to like_comments_path(
    like: {
      good_or_bad: "good",
      comment_id: comment.id,
    }), remote: true, method: :post do %>
    <i class="material-icons light-blue-text text-lighten-4">thumb_up</i>
  <% end %>
</div>
<div class="col s6 center">
  <%= link_to like_comments_path(
    like: {
      good_or_bad: "bad",
      comment_id: comment.id
    }), remote: true, method: :post do %>
    <i class="material-icons light-blue-text text-lighten-4">thumb_down</i>
  <% end %>
</div>

app/views/comments/_good_like.html.erb
<div class="col s6 center">
  <%= link_to like_comments_path(
    like: {
      good_or_bad: "",
      comment_id: comment.id,
    }), remote: true, method: :post do %>
    <i class="material-icons light-blue-text text-lighten-1">thumb_up</i>
  <% end %>
</div>
<div class="col s6 center">
  <%= link_to like_comments_path(
    like: {
      good_or_bad: "bad",
      comment_id: comment.id
    }), remote: true, method: :post do %>
    <i class="material-icons light-blue-text text-lighten-4">thumb_down</i>
  <% end %>
</div>

app/views/comments/_like_form.html.erb
<% if comment.good_or_bad?(user) == "" %>
  <%= render('comments/both_unlike', comment: comment) %>
<% elsif comment.good_or_bad?(user) == "bad" %>
  <%= render('comments/bad_like', comment: comment) %>
<% elsif comment.good_or_bad?(user) == "good" %>
  <%= render('comments/good_like', comment: comment) %>
<% end %>

app/views/comments/create.js.erb
$("#comment-form").before("<%= escape_javascript(render('posting_threads/comment', comment: @comment, posting_thread: @posting_thread)) %>");
 $("#comment_content").val("");

app/views/comments/like.js.erb
<% if @like.good_or_bad == "good" %>
  $(".like-<%= @like.comment.id %>").empty().append("<%= escape_javascript(render('good_like', comment: @like.comment)) %>")
<% elsif @like.good_or_bad == "bad" %>
  $(".like-<%= @like.comment.id %>").empty().append("<%= escape_javascript(render('bad_like', comment: @like.comment)) %>")
<% elsif @like.good_or_bad == "" %>
  $(".like-<%= @like.comment.id %>").empty().append("<%= escape_javascript(render('both_unlike', comment: @like.comment)) %>")
<% end %>