config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations',
    passwords: 'users/passwords', confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  root 'home#index'

  namespace :users do
    resource :profiles, only: :show
  end
  resources :posting_threads
  resources :comments, only: [:create, :update, :destroy] do
    collection do
      post 'like'
    end
  end
  resources :search, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.eager_load(:posting_threads).order('posting_threads.updated_at desc')
  end
end

app/views/home/index.html.erb
<div class="home-image">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <div class="card-panel amber lighten-2 home-panel-thread">
          <div class="center">
            <h3 class="thread-home-title">色んな話題について<br>みんなで語り合おう！！</h3>
            <%= link_to new_posting_thread_path, class: "waves-effect waves-light btn-large light-blue lighten-2", data: {"turbolinks" => false} do %>
            <i class="material-icons large right">speaker_notes</i>
            スレを立てる
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col s6">
      <%= link_to posting_threads_path do %>
        <h4 class="section center black-text">新着スレ</h4>
      <% end %>
      <div class="divider"></div>
      <div class="row section">
        <div class="col s12">
          <div class="card-panel">
            <div class="row">
              <% PostingThread.recent(4).each do |thread| %>
              <div class="col s12">
                <%= link_to posting_thread_path(thread) do %>
                <h5>
                  <%= thread.title %>
                  <small class="right grey-text"><%= thread.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
                </h5>
                <div class="divider"></div>
                <% end %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col s5 right">
      <h4 class="section center">スレッドを探す</h4>
      <div class="divider"></div>
      <%= form_tag controller: "search", action: "create", method: "post", class: "col s12" do %>
        <div class="row modal-form-row">
          <div class="input-field col s12">
            <%= text_field_tag :search_word %>
            <%= label_tag :search_word %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= select_tag(:categories, options_from_collection_for_select(Category.all, :id, :name), { multiple: true }) %>
            <%= label_tag :categories, 'カテゴリー' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12 center">
            <%= submit_tag("検索", class: "modal-action modal-close light-blue lighten-2 btn") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col s12">
      <h4 class="section center">カテゴリー別</h4>
      <div class="divider"></div>
      <div class="row category">
        <% @categories.each do |category| %>
          <div class="col s6">
            <div class="section">
              <ul class="collection with-header card">
                <li class="collection-item amber lighten-2 center"><strong><%= link_to category.name, posting_threads_path(category: category.id) %></strong></li>
                <% category.posting_threads.first(3).each do |thread| %>
                  <li class="collection-item">
                    <%= link_to thread.title, posting_thread_path(thread.id) %>
                    <span class="right grey-text"><%= thread.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>