config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations',
    passwords: 'users/passwords', confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  root 'home#index'

  namespace :users do
    resource :profiles, only: :show
  end
  resources :posting_threads
  resources :comments, only: [:create, :update, :destroy] do
    collection do
      post 'like'
    end
  end
  resources :search, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/posting_thread.rb
class PostingThread < ApplicationRecord
  has_many :comments, dependent: :destroy, inverse_of: :posting_thread
  has_many :posting_thread_categories, dependent: :destroy, inverse_of: :posting_thread
  has_many :categories,
            through: 'posting_thread_categories',
            source: 'category'
  accepts_nested_attributes_for :posting_thread_categories
  belongs_to :user

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 500 }
  validates :user_id, presence: true
  scope :filter_by_categories, ->(categories_name) do
    self.joins(:categories).
      where("#{Category.table_name}.name IN (?)", categories_name)
  end

  scope :recent, ->(display_amount) { order(created_at: 'desc').limit(display_amount) }
  scope :filter_by_words_with_exclusion, ->(regexp_word, exclusion_ids) do
    joins(:comments, :categories).
      where("#{PostingThread.table_name}.title Like :this OR #{PostingThread.table_name}.description Like :this OR #{Comment.table_name}.content Like :this OR #{Category.table_name}.name Like :this", this: regexp_word).
      where.not(id: exclusion_ids).
      select("#{PostingThread.table_name}.*, count(#{Comment.table_name}.id) as comments_count").
      group(:id).order("comments_count desc")
  end

  def self.text_match(words)
    regexp =  words.split(/[ 　\t]/).map{ |a| "%#{a.strip}%" }
    exclusion_ids = []
    threads = []
    regexp.each do |regexp_word|
      threads << PostingThread.filter_by_words_with_exclusion(regexp_word, exclusion_ids)
      exclusion_ids << threads.flatten.map(&:id).uniq
    end
    threads.flatten
  end

  def rating
    self.all_good_count - self.all_bad_count
  end

  def all_good_count
    all_count = 0
    comments.each do |comment|
      all_count += comment.good_count
    end
    all_count
  end

  def all_bad_count
    all_count = 0
    comments.each do |comment|
      all_count += comment.bad_count
    end
    all_count
  end

  def user?(current_user)
    self.user == current_user
  end
end

app/controllers/posting_threads_controller.rb
class PostingThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @category = Category.find_by id: params[:category]
    @posting_threads = ThreadSearchForm.filter_by_category_or_new_arrival(@category, params[:page])
  end

  def show
    @current_user = current_user
    @posting_thread = PostingThread.find params[:id]
    @comments = @posting_thread.comments.includes(:user)
  end

  def new
    @user = current_user
    @posting_thread = PostingThread.new
    @posting_thread.posting_thread_categories.build
  end

  def create
    @user = current_user
    @posting_thread = PostingThread.create(posting_threads_params)
    if @posting_thread.valid?
      params_categories_ids = categories_params[:category_id]
      params_categories_ids.shift
      params_categories_ids.each do |id|
        PostingThreadCategory.find_or_create_by(category_id: id, posting_thread_id: @posting_thread.id)
      end
      redirect_to @posting_thread, notice: "スレッドを立てました。"
    else
      render 'new'
    end
  end

  def edit
    @posting_thread = current_user.posting_threads.find params[:id]
  end

  def update
    @posting_thread = PostingThread.find params[:id]
    if @posting_thread.update(posting_threads_params)
      params_categories_ids = categories_params[:category_id]
      params_categories_ids.shift
      db_categories = @posting_thread.posting_thread_categories
      db_categories.each do |category|
        category.destroy unless params_categories_ids.include?(category.id)
      end
      params_categories_ids.each do |id|
        PostingThreadCategory.find_or_create_by(category_id: id, posting_thread_id: @posting_thread.id)
      end
      redirect_to @posting_thread, notice: "スレッドを更新しました。"
    else
      render 'edit'
    end
  end

  def destroy
    posting_thread = current_user.posting_threads.find params[:id]
    posting_thread.destroy
    redirect_to root_path, alert: "「#{posting_thread.title}」を削除しました。"
  end

  private

    def posting_threads_params
      params.require(:posting_thread).permit(
        :user_id,
        :title,
        :description,
      )
    end

    def categories_params
      params.require(:posting_thread_categories).permit(category_id: [])
    end
end

app/views/posting_threads/_comment.html.erb
<div class="row comment-content">
  <div class="col s9">
    <p><%= comment.poster %></p>
    <p><strong><%= simple_format(comment.content) %></strong></p>
  </div>
  <div class="col s3">
    <div class="row">
      <div class="col s12 center">
        <p><span class="grey-text"><%= comment.updated_at.strftime("%Y-%m-%d %H:%M") %></span></p>
      </div>
      <div class="like-<%= comment.id %>">
        <%= render('comments/like_form', comment: comment, user: current_user) if current_user %>
      </div>
    </div>
  </div>
</div>
<div class="divider"></div>

app/views/posting_threads/edit.html.erb
<div class="container">
  <h1 class="title">スレッド編集</h1>
  <p class="center user-confirmation"></p>
  <div class="row">
    <div class="input-field col s12">
      <%= form_with model: @posting_thread, local: true do |f| %>
        <%= render "shared/error_messages", resource: f.object %>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :title, class: "autocomplete",  data: { length: "100" } %>
            <%= f.label :title, 'タイトル' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_area :description, class: "materialize-textarea",  data: { length: "500" } %>
            <%= f.label :description, '詳細' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= collection_select(:posting_thread_categories, :category_id, Category.all, :id, :name, { selected: @posting_thread.categories.ids },{ multiple: true }) %>
            <%= label_tag :posting_thread_categories, 'カテゴリー' %>
          </div>
        </div>
        <div class="row">
          <div class="actions input-field col s6">
            <%= f.submit "スレッド更新", class: "btn waves-effect waves-light" %>
          </div>
          <div class="actions input-field col s6">
            <%= link_to "スレッド削除", posting_thread_path(@posting_thread), method: :delete, class: "btn waves-effect waves-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posting_threads/index.html.erb
<div class="container">
  <div class="section">
    <h3 class="center"><%= @category ? @category.name : '新着スレッド' %></h3>
  </div>
  <div>
    <div class="divider"></div>
    <div class="section">
      <%= render 'shared/posting_threads', posting_threads: @posting_threads, display_amount: 3 %>
    </div>
  </div>
</div>

app/views/posting_threads/new.html.erb
<div class="container">
  <h1 class="title">スレを立てよう！！</h1>
  <p class="center user-confirmation"></p>
  <div class="row">
    <div class="input-field col s12">
      <%= form_with model: @posting_thread, local: true do |f| %>
        <%= f.hidden_field :user_id, value: @user.id %>
        <%= render "shared/error_messages", resource: f.object %>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :title, class: "autocomplete", data: { length: "100" } %>
            <%= f.label :title, 'タイトル' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= f.text_area :description, class: "materialize-textarea",  data: { length: "500" } %>
            <%= f.label :description, '詳細' %>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <%= collection_select(:posting_thread_categories, :category_id, Category.all, :id, :name, {}, { multiple: true }) %>
            <%= label_tag :posting_thread_categories, 'カテゴリー' %>
          </div>
        </div>
        <div class="row">
          <div class="actions input-field col s12">
            <%= f.submit "新しいスレッド作成", class: "btn light-blue lighten-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posting_threads/show.html.erb
<div class="thread-title amber lighten-2">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <h3 class="center">
          <%= @posting_thread.title %>
          <%= link_to edit_posting_thread_path, class: "edit-thred-link", data: {"turbolinks" => false} do %>
            <i class="material-icons">mode_edit</i>
          <% end if @posting_thread.user?(@current_user) %>
        </h3>
      </div>
      <div class="col s7">
        <p><%= simple_format(@posting_thread.description) %></p>
      </div>
      <div class="col s5 center">
        <p>カテゴリー　：　<%= @posting_thread.categories.pluck(:name).join(' , ') %></p>
        <p><%= @posting_thread.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="divider"></div>
  <% @comments.each do |comment| %>
    <%= render 'comment', comment: comment, current_user: @current_user %>
  <% end %>
  <% if @current_user %>
    <%= form_with model: Comment.new, id: "comment-form" do |form| %>
      <%= form.hidden_field :posting_thread_id, value: @posting_thread.id %>
      <div class="row section">
        <div class="col s10 input-field">
          <%= form.text_area :content, class: "materialize-textarea", data: { length: "200" } %>
          <%= form.label :content, 'コメント' %>
        </div>
        <div class="col s2 input-field">
          <%= form.submit "コメント", class: "btn waves-effect waves-light right" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="row section">
      <div class="col s12">
        <%= link_to new_user_session_path do %>
          <div class="center red-text not-comment">
            <h5>コメントするためにはユーザーのログインが必要です。</h5>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>