config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions', registrations: 'users/registrations',
    passwords: 'users/passwords', confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }
  root 'home#index'

  namespace :users do
    resource :profiles, only: :show
  end
  resources :posting_threads
  resources :comments, only: [:create, :update, :destroy] do
    collection do
      post 'like'
    end
  end
  resources :search, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_message.html.erb
<% if flash.present? %>
  <div class="flash-message">
    <% flash.each do |key, value| %>
      <%= content_tag(:p, value, class: "flash-#{key}") %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper amber">
        <div class="container">
          <%= link_to "10ch", root_path, class: "brand-logo logo", data: {"turbolinks" => false} %>
          <ul id="nav-mobile" class="right">
            <% if user_signed_in? %>
              <li><%= link_to "ユーザーページ", users_profiles_path %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TenChannel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </body>
</html>